widdowquinn/pyani

tests/test_concordance.py
This should also apply cleanly to the v0.2 branch where much of the Python 3 work is happening, see #12.
=> Python 3 ready printing in test_concordance.py

pyani/pyani_graphics.py
Note: Pull request is against the v0.2 development branch, it would need tweaking to apply to the current master branch.
Use case: Have output from ``genbank_get_genomes_by_taxon.py`` which writes ``classes.txt`` and ``labels.txt`` but added one or two local FASTA files without updating the caption files.
This commit avoids getting a nasty KeyError (although perhaps a warning would be better?)
=> Cope with missing labels

CHANGES.md, genbank_get_genomes_by_taxon.py
Updates the escaping of genome names for downloaded files (converting commas to underscores; NCBI don't use percent escapes for URLs for their FTP downloads), and adds code to try to correct for download errors due to RefSeq sequence suppression, or removed GenBank files. Where correction is not possible, the output log tries to be verbose and helpful.
=> Genbank download escapes

average_nucleotide_identity.py, genbank_get_genomes_by_taxon.py, pyani/pyani_graphics.py
These changes implement a more graceful handling of errors/
omissions in the classes.txt file. Individual input sequences that
are not in the classes.txt file are now treated as single classes
for the colour bars. Also, the average_nucleotide_identity.py
script now warns if there are misformatted lines in classes.txt
=> enable graceful replacement of classes for input not in classes.txt

average_nucleotide_identity.py
Adds `pyani` version to log output, and fixes a bug where absent labels/classes files would throw an error.
=> add pyani version to log output

.travis.yml, pyani/anib.py, tests/test_concordance.py, tests/test_dependencies.py
These commits collectively modify Travis CI settings to install binary dependencies, and make the concordance tests work both locally and on Travis CI.
=> make tests of binary dependencies work

bin/average_nucleotide_identity.py, pyani/pyani_graphics.py
Issue #49 was fixed as per @ytanizaw's suggestion in the issues
The matplotlib bug was due to a stricter reading of the `height_ratios`
argument in GridSpec.
=> fix issue #49, TETRA analysis failure; also matplotlib update bug

CHANGES.md, bin/average_nucleotide_identity.py, pyani/anim.py, requirements.txt
`average_nucleotide_identity.py` now pays attention to the `--maxmatch` option and passes it through to the command-line constructor.
=> fix for Issue 53

bin/average_nucleotide_identity.py
This would partly address #65 
Code change based on https://docs.python.org/3/library/argparse.html example, gives:
```
$ average_nucleotide_identity.py --version
average_nucleotide_identity.py using pyani 0.2.3
```
I have not made a similar change to genbank_get_genomes_by_taxon.py as it does not actually use the pyani libraries.
It might be sensible to give both scripts their own version numbers separate from the pyani library version?
=> Add --version switch to average_nucleotide_identity.py

bin/genbank_get_genomes_by_taxon.py
I had an exception where ``URLError`` was thrown with a reason of timeout. It seems that ``socket.timeout`` may not get used as an exception, rather as a reason?
Unfortunately on retesting the timeout seemed to go away...
=> Change how catch FTP timeouts

bin/genbank_get_genomes_by_taxon.py
e.g. using txid 613 problem cases include:
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/564/475/GCA_001564475.1_12082_3#81/GCA_001564475.1_12082_3#81_genomic.fna.gz
-->
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/564/475/GCA_001564475.1_12082_3_81/GCA_001564475.1_12082_3_81_genomic.fna.gz
and:
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/468/075/GCA_000468075.1_Serratia_fanticola_AU-P3(3)/GCA_000468075.1_Serratia_fanticola_AU-P3(3)_genomic.fna.gz
-->
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/468/075/GCA_000468075.1_Serratia_fanticola_AU-P3_3_/GCA_000468075.1_Serratia_fanticola_AU-P3_3__genomic.fna.gz
With this change I went from approx 204 genomes to 410 genomes for tax id 613 (with two failures which both had status files saying they had been replaced).
=> Must escape hash and brackets too for NCBI FTP URL

bin/average_nucleotide_identity.py
Use case: Typo in either filename results in pyani computing all the comparisons, and then crashing when it comes to draw plots.
=> Fail immediately if specified label or classes file missing

bin/average_nucleotide_identity.py
Currently get:
```
INFO: command-line: ...
INFO: Input directory: interesting_serratia
INFO: Removing directory interesting_serratia_cmp and everything below it
WARNING: NOCLOBBER: not actually deleting directory
...
```
With this change get:
```
INFO: command-line: ...
INFO: Input directory: interesting_serratia
WARNING: NOCLOBBER: not actually deleting directory interesting_serratia_cmp
...
```
This removes the scary message ;)
There is scope for further simplification here when (re)creating the directories...
=> Remove logging about removing dir with NOCLOBBER

CHANGES.md, bin/genbank_get_genomes_by_taxon.py
The issue reported was that the `--format` argument did not work for
downloading GenBank files. I had overlooked reimplementation of this
when adapting code for the new NCBI layouts. The lesson here is that
tests need to cover scripts (and this was already in process under
the `classify` branch).
=> fix issue #89

CHANGES.md, bin/average_nucleotide_identity.py, pyani/anim.py, pyani/pyani_config.py, tests/test_cmdlines.py
This issue arose because with NUCmer alignment some regions were
being aligned twice or more (e.g. repeats) and all alignments
contributed to the ANIm calculations. This is fixed here by
adding a delta-filter -1 step to the process, to restrict each
region of the genome to participate in only a single alignment.
=> fix issue #91 - incorrect coverage and %ID with ANIm

bin/genbank_get_genomes_by_taxon.py
GenBank download script now insists on integer input for
--batchsize, --retries, and --timeout
=> fix issue #97 (wrong script input types)

.travis.yml, bin/delta_filter_wrapper.py, pyani/anim.py, setup.py, tests/test_cmdlines.py, tests/test_concordance.py
These changes fix issue #99 where ANIm jobs did not run on our SGE/OGE cluster.
The solution breaks the nucmer and delta-filter jobs into separate submissions, where the delta-filter job depends on a corresponding nucmer job. This has been confirmed to solve the issue on our cluster, and does not affect multiprocessing runs.
Unfortunately, some new incompatibility with TravisCI means that I've disabled the concordance tests. I haven't chased that down yet, but the tests run correctly on my laptop and the cluster, and all other tests (including parsing) run correctly.
=> Fix to Issue 99

docs/examples.rst
Take #2:  Add example usage for `pyani index` to the readthedocs "Examples" page.
=> Add index example

.travis.yml, CHANGES.md, pyani/anib.py, tests/test_anib.py, tests/test_concordance.py, tests/test_dependencies.py, tests/test_multiprocessing.py
The legacy BLAST executables are no longer available from NCBI's FTP site, and they cannot be integrated into Travis CI for testing. Therefore all testing for ANIblastall is now skipped.
In addition, we add Python 3.7 test support to TravisCI.
=> Disable blastall

docs/subcmd_download.rst, pyani/download.py, pyani/pyani_graphics.py, pyani/scripts/parsers/download_parser.py, pyani/scripts/pyani_script.py, pyani/scripts/subcommands/subcmd_download.py, requirements-dev.txt, tests/test_graphics.py, tests/test_legacy_scripts.py, tests/test_subcmd_01_download.py, tests/test_subcmd_08_anib.py
This change allows the user to specify an NCBI API key when using `pyani download` (see [https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/](https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/)) which increases the allowed Entrez request rate.
This PR closes #157.
=> add `--api_key` option to `pyani download`

pyani/scripts/subcommands/subcmd_aniblastall.py, pyani/scripts/subcommands/subcmd_index.py, tests/test_subcmd_02_index.py
Fixes #206 by removing the logger argument from subcmd_index().
There was a similar problem waiting in subcmd_aniblastall(), too,
so that was fixed also.
=> fix #206 and remove unnecessary logger arguments to subcommands

pyani/run_sge.py, pyani/scripts/subcommands/subcmd_anim.py
Fixes two bugs introduced when reformatting strings/changing logger style.
These were missed as SGE runs are not yet under CI in CircleCI.
The main fixing change is to remove the logger argument from
run_sge.run_dependency_graph(). No logger was being passed, so this
broke SGE command construction.
A second addition here was to explicitly check for SGE being specified as
scheduler.
A minor related fix was to correct an fstring output.
=> fix issue #212 (SGE jobs not running)

.circleci/config.yml
Adding Python 3.8 to the test regime is useful, and scheduling a weekly test means we won't let third-party/other changes cryptically bork things if it's a long time between pushes.
=> Add Python 3.8 to CircleCI matrix, and schedule weekly test

setup.py
This should fix #244, which was preventing correct installation using
`python setup.py install` and `pip install -e .`
=> add sqlalchemy to setup.py - fix #244

README.md, README_v_0_2_x.md
These documentation changes are intended to clarify that the default GitHub branch is the development version (v0.3), and that `conda`/`pip` will install the stable version (0.2).
While writing it, I thought that the *better* choice would be to restore `version_0_2` as the `default` branch on `GitHub` and write its documentation accordingly.
If we agree on that, I propose we accept the documentation changes here as an interim measure, then start a new issue to change over the default branch and update the documentation to reflect that.
=> (Partial) Fix #240

pyani/scripts/pyani_script.py
The `pyani_script.run_main()` function had a logic error where in all cases that `sys.argv` contained only the empty string, the `pyani` version info would be returned. As calls to `run_main()` passing arguments did not update `sys.argv` all calls to `run_main()` from test code or when profiling would return the `pyani` version and exit, rather than running the application.
This fix checks to see if, when `sys.argv` is "empty", some arguments may have been passed in the function call. If so, the `pyani` version statement is not shown, and the code runs.
=> fix #287 - allows empty sys.argv if arguments passed

pyani/anim.py, pyani/pyani_files.py, pyani/pyani_orm.py, pyani/scripts/subcommands/subcmd_anib.py, pyani/scripts/subcommands/subcmd_anim.py, pyani/scripts/subcommands/subcmd_plot.py
I found anim was not reusing pre-existing files.
My fix was using Path object directly, not just the filename (which discards the path information). Could alternatively have built or converted the expected list into filenames only?
Also turns the list of Path objects into a set for a slight speed up (addresses a TODO comment), and adds a bit more debugging.
As far as I can see, anib does not support recovery mode (untested)?
=> Fix anim recovery mode

.circleci/config.yml
Fixes the breakpoint in the CircleCI tests that have been cropping up. Getting it merged into `master` quickly seems like it should be a priority.
Closes #330.
=> Fix CircleCI `apt-get update` test breaker

CONTRIBUTING.md, docs/contributing.rst
Mention this very useful line of code that developers might like to know about.
I think the wording probably needs to be different, particularly in `CONTRIBUTING.md`—I think this is still not completely clear on the distinction between setting up an environment versus a local repo that can be actively modified, but talking it through might help.
Closes #316.
=> Mention `pip install -e .` in install instructions for developers

tests/test_anib.py
Fixes a pytest warning related to pandas
=> fix warning in test_anib.py

pyani/scripts/subcommands/subcmd_anib.py, pyani/scripts/subcommands/subcmd_anim.py
Noticed while investigating #353 for which I intend to add a little more logging.
=> Fix a typo in logging message & redundant f-string usage

pyani/scripts/parsers/report_parser.py
This PR tries to improve the command line help text for ``pyani report`` options ``--run_results`` & ``--run_matrices``. Before:
```
$ pyani report --help
...
--run_results RUN_RESULTS
Report table of results for a pyani run (default:
False)
--run_matrices RUN_MATRICES
Report matrices of results for a pyani run (default:
False)
...
```
After:
```
$ pyani report --help
...
--run_results RUN_ID  Report table of results for comma separated list of
runs (default: False)
--run_matrices RUN_ID
Report matrices of results for comma separated list of
runs (default: False)
...
```
This documents that these arguments can be comma separated lists.
The choice of metavariable name is to match ``pyani plot``:
```
$ pyani plot --help
...
--run_id RUN_ID       run ID to plot (default: None)
...
``` …
=> Clarify command line help for report --run_results & --run_matrices

pyani/pyani_tools.py
Closed #357 - matrix output is not applying labels, e.g. example with 17 genomes:
```
$ head -n 1 matrix_identity_1.tab 
1:1	2:2	3:3	4:4	5:5	6:6	7:7	8:8	9:9	10:10	11:11	12:12	13:13	14:14	15:15	16:16	17:17
```
The problem is a string vs integer mapping, cross reference b54106f36428f017a2589b05de33c0a6d3ed9ea4 (15 Oct 2019) addressing a similar issue with Seaborn plotting.
Where might a test be best added?
=> Fix genome labels in matrix output

pyani/anim.py, pyani/pyani_files.py, pyani/scripts/subcommands/subcmd_anim.py, tests/conftest.py, tests/test_anim.py
This explicitly sorts the FASTA file lists to ensure the genome list is sorted prior to building an all-vs-all matrix. This is important for symmetric methods like anim so that we consistently run ``A_vs_B`` rather than ``B_vs_A`` and thus recovery mode will work stably regardless of the genome order on disk (e.g. cached files have been moved/copied).
Resolves #353 (where examples of both ``A_vs_B`` and ``B_vs_A`` were found on disk).
=> Sort genomes (for stable anim recovery mode)

pyani/scripts/subcommands/subcmd_anim.py
Resolves an error in a logging command which is not caught by tests, but which `codefactor` complains about.
=> Can't reference `run_id` if the run fails

requirements-thirdparty-macos.txt
The macOS Perl hashbang issue was fixed in bioconda in August https://github.com/bioconda/bioconda-recipes/issues/28209
=> Drop pinning on mummer=3.23=h6de7cb9_11 for macOS
