- pyani/run_sge.py
- tests/test_concordance.py
Tested on the v0.2 branch, but could apply this to the master instead if you preferred.
Branch includes a print fix from #17 as well.
> Replace file(...) with open(...) for Python 3

- .codecov.yml
- .travis.yml
- MANIFEST.in
- README.md
- pyani/__init__.py
- requirements.txt
- setup.py
- tests/test_concordance.py
- tests/test_dependencies.py
- tests/test_parsing.py
Added TravisCI testing, and codecov.io coverage monitoring.
> Test updates

- .travis.yml
- genbank_get_genomes_by_taxon.py
- tests/test_scripts.py
Moves MUMmer installation from source install to apt-get.
Refactors `test_scripts.py`.
> Test mummer

- average_nucleotide_identity.py
- genbank_get_genomes_by_taxon.py
- pyani/anib.py
- pyani/pyani_graphics.py
- pyani/pyani_jobs.py
- pyani/run_sge.py
- tests/test_scripts.py
Fixes a range of code smells and errors reported by `landscape.io`.
> Landscaping

- README.md
- average_nucleotide_identity.py
- pyani/pyani_graphics.py
Remove support for R graphics output.
> Remove rpy

- README.md
Also using one line per badge in the markdown, looks the same but should be easier to edit
> Make README badges all clickable

- pyani/anim.py
- tests/test_failing_data/README.md
See #72.
See also #73 which comes up in the existing test case which I used here for validating my proposed fix.
> Remove repeated error message

- bin/average_nucleotide_identity.py
- bin/genbank_get_genomes_by_taxon.py
This should help anyone else picking the SGE batch size.
Also marks the input/output directories as required.
> Explain default arguments in CLI help

- CHANGES.md
- pyani/pyani_graphics.py
- distance matrices are converted from square to condensed form for linkage analysis
- `matplotlib` calls use new API ('false', 'off' -> False; 'true', 'on' -> True)
> Fix Issue #120

- bin/genbank_get_genomes_by_taxon.py
Add functionality ('-s' flag) to put downloaded files into named species subfolders instead of all in one parent folder. Just an example bit of code, not rigorously tested and could handle subspecies folders better, but it works.
> Add -s flag for species subfolder creation

- pyani/pyani_graphics.py
- pyani/scripts/subcommands/subcmd_plot.py
This PR adds production of distribution plots for each of the usual heatmap outputs. These are written in the same location as the heatmaps.
> add distribution plot outputs for pyani plot subcommand

- README.md
- README_v_0_2_x.md
This commit fixes issue #166 and #165
> add README for v0.2.x documentation and link from current README

- pyani/anib.py
- pyani/aniblastall.py
- pyani/dependencies.py
- pyani/download.py
- pyani/scripts/parsers/__init__.py
- pyani/scripts/parsers/listdeps_parser.py
- pyani/scripts/subcommands/subcmd_listdeps.py
Adds `pyani listdeps` command, which details installed (and not-installed) modules, their version numbers and install location. This closes #173.
> Add `pyani listdeps` command

- pyani/scripts/parsers/common_parser.py
- pyani/scripts/pyani_script.py
This PR should close #67 by providing CITATION info with the `--citation` argument. The README.md change was implemented in a prior PR (190b441).
> add --citation argument to common pyani argparser

- docs/citations.rst
Add citations for January 2021.
> add recent (Jan 2021) citations

- README.md
Just some random typos I found. I'm still going over some other files, though.
> Fixing grammar/spelling

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #280. Adds another option to the top section of the PR template for documentation changes.
> Fixes issue 280: Added an option for documentation updates to PR template

- .circleci/config.yml
Now we test:
py3.9.5
py3.8.9
py3.7.10
py3.6.9
This keeps use relatively up-to-date at CircleCI for weekly and spot tests.
> update CircleCI config (add py39, update images)

- README.md
Fixes #222. Added notes about using `pyani plot` with large numbers of genomes, recommending use of `--method mpl`; based on discussion in #222.
> Fixes issue 222: Added note relating to use of `pyani plot` with large numbers of genomes

- pyani/scripts/genbank_get_genomes_by_taxon.py
Fixes #70. This PR is admittedly based on a very old issue, which didn't include any information about versions/how to reproduce/traceback. It may need more testing, but I haven't yet figured out how to go about accomplishing that.
> Fixes issue 70: Notify user when ftp download fails because the file has been replaced

- pyani/anim.py
- tests/test_anim.py
Merging #217 was premature - a handful of tests failed with those changes.
This PR should fix #294
> fix #294 - errors due to merging of #217

- README.md
- docs/index.rst
- docs/scheduler.rst
- docs/using_a_scheduler.rst
Fixes #179. Added description of `pyani` usage with an SGE scheduler, based on discussion in #179, and the contents of `run_sge.py`, (plus my own knowledge of SGE).
> Fixes issue 179: Add notes on SGE usage to `README.md`

- README.md
- docs/download.rst
- docs/indexing.rst
- docs/quickstart.rst
`pyani` now retains the original extension when hash files are created; this PR changes the docs and Readme  to reflect this.
Close #300.
> Issue 300: Update `.md5` file names in docs

- pyani/pyani_tools.py
- pyani/scripts/parsers/plot_parser.py
- pyani/scripts/parsers/report_parser.py
- pyani/scripts/parsers/scheduling_parser.py
Shows possible choices for parser options in help output.
> Parser choices

- pyani/pyani_tools.py
- pyani/scripts/parsers/plot_parser.py
- pyani/scripts/parsers/report_parser.py
- pyani/scripts/parsers/scheduling_parser.py
Reverts widdowquinn/pyani#359
Need to undo the merge of #358.
> Revert "Parser choices"

- .flake8
- pyani/pyani_report.py
- pyani/pyani_tools.py
- pyani/scripts/parsers/report_parser.py
- pyani/scripts/subcommands/subcmd_report.py
- tests/test_subcmd_05_report.py
This is a recreation of #358, which was prematurely merged, and has been reverted, but which I couldn't re-open.
Closes #357 - matrix output is not applying labels, e.g. example with 17 genomes:
```
$ head -n 1 matrix_identity_1.tab 
1:1	2:2	3:3	4:4	5:5	6:6	7:7	8:8	9:9	10:10	11:11	12:12	13:13	14:14	15:15	16:16	17:17
```
The problem is a string vs integer mapping, cross reference b54106f36428f017a2589b05de33c0a6d3ed9ea4 (15 Oct 2019) addressing a similar issue with Seaborn plotting.
Where might a test be best added?
> Issue #357: Fix genome labels in matrix output

- docs/subcmd_plot.rst
- docs/subcmd_report.rst
- pyani/scripts/parsers/plot_parser.py
- pyani/scripts/parsers/report_parser.py
- pyani/scripts/parsers/scheduling_parser.py
- pyani/scripts/subcommands/subcmd_plot.py
- pyani/scripts/subcommands/subcmd_report.py
- tests/test_subcmd_05_report.py
- tests/test_subcmd_06_plot.py
This lists the available choices for parser options, as well as modifying how options that accept multiple values parse what they are passed.
> Explicitly list parser choices in `help` output

- pyani/pyani_report.py
Adds a `try/except` around the end of `write_dbtable()` to catch `ModuleNotFoundError`s. The added `try/except` triggers some `logger.warning` statements that inform the user of the missing module (and provide the error message), and that the current format will be skipped. The loop then continues.
This allows other output formats that do not require the missing module to still be written.
Closes #130.
> Issue #130: Add `try/except` to catch `ModuleNotFoundError` when no `openpyxl`

- pyani/dependencies.py
Adds `fastANI` to the output of `pyani listdeps`.
Closes #379.
> Report `fastANI` version in `pyani listdeps` output

- .circleci/config.yml
- Makefile
- pytest.ini
- requirements-dev.txt
- requirements-pip.txt
- tests/conftest.py
- tests/test_dependencies.py
- tests/test_fastani.py
- tests/test_legacy_scripts.py
- tests/test_subcmd_04_anim.py
- tests/test_subcmd_05_report.py
- tests/test_subcmd_06_plot.py
- tests/test_subcmd_07_classify.py
Update CircleCI config so that caching is separated out by Python version.
Also add Python 3.10 tests.
> Update CircleCI config and related files

- CONTRIBUTING.md
> Update docs - CI now GitHub Actions

- pyani/pyani_orm.py
Was using an undefined attribute
> Fix percentage identity in Comparison __str__

- pyani/pyani_orm.py
Addresses an issue found at https://github.com/pyani-plus/pyani-plus/pull/129
> Default diagonal for sim-errors should be zero
